name: Docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "src/**"
      - "pyproject.toml"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"
      - "src/**"
      - "pyproject.toml"
      - ".github/workflows/docs.yml"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: docs-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project + docs deps
        run: |
          python -m pip install -U pip
          pip install .
          pip install -r docs/requirements.txt

      - name: Build Sphinx HTML
        env:
          IDUEDU_DOCS_CI: "1"
        run: |
          sphinx-build -E -b html docs docs/_build/html --keep-going

      - name: Upload docs artifact (for PR preview)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

  deploy-docs:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download built docs
        uses: actions/download-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages
          force_orphan: true
